### ISSUE TITLE
Does not display characters properly

### ISSUE THREAD

**Issue by M0T0FAM93** [KwalaGamer/qb-multicharacter#2]
Nice work! 1 issue i noticed is it will ALWAYS display default characters instead of updated characters, even thou i have created new character and changed clothe
![unknown](https://user-images.githubusercontent.com/100702772/157080081-363a3a39-57f6-4333-870e-415d67f373d1.png)
s

**Comment by M0T0FAM93** [comment]
also will show female for males and males for females...etc

**Comment by KwalaGamer** [comment]
Send Screen Shot

**Comment by shivamhans** [comment]
2.0 Coming SOON 😊
